### ISSUE TITLE
Could not fork more than 300. `Kernel.sem` limit.

### ISSUE THREAD

**Issue by Moln** [misterion/ko-process#24]
Test code:

```php
$manager = new Ko\ProcessManager();
for ($i = 0; $i < 300; $i++) {
    $manager->fork(function(Ko\Process $p) {
        echo 'Hello from ' . $p->getPid() . "\n";
        sleep(1);
        exit(1); //exit with non 0 exit code
    });
}
$manager->wait();
```

Result:

```shell
[root@host-192-168-113-41 demo]# php pcntl.php 
Hello from 9167
......
Hello from 9290

Warning: sem_get(): failed for key 0x61003ddc: No space left on device in /var/www/html/queue/vendor/misterion/ko-process/src/Ko/Semaphore.php on line 79

Fatal error: Uncaught RuntimeException: Unable to create the semaphore in /var/www/html/queue/vendor/misterion/ko-process/src/Ko/Semaphore.php:81
Stack trace:
#0 /var/www/html/queue/vendor/misterion/ko-process/src/Ko/SharedMemory.php(90): Ko\Semaphore->__construct(1627405788)
#1 /var/www/html/queue/vendor/misterion/ko-process/src/Ko/ProcessManager.php(195): Ko\SharedMemory->__construct()
#2 /var/www/html/queue/vendor/misterion/ko-process/src/Ko/ProcessManager.php(189): Ko\ProcessManager->createProcess(Object(Closure))
#3 /var/www/html/queue/demo/pcntl.php(34): Ko\ProcessManager->fork(Object(Closure))
#4 {main}
  thrown in /var/www/html/queue/vendor/misterion/ko-process/src/Ko/Semaphore.php on line 81
```

**Comment by misterion** [comment]
Hi Moln. Please, look at this question http://unix.stackexchange.com/questions/75547/how-to-get-proccesses-currently-running-semaphores-by-proc
